#+TITLE: Oh My Emacs Advanced
#+OPTIONS: toc:2 num:nil ^:nil

This is part of the [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]].

This file contains some advanced features or packages which could make emacs
look unlike emacs. So ensure you have some basic knowledge and experience
before loading this file.

* Prerequisites
  :PROPERTIES:
  :CUSTOM_ID: advanced-prerequisites
  :END:

#+NAME: advanced-prerequisites
#+CAPTION: Prerequisites for ome-advanced module
|          | Windows | Ubuntu/Debian/Mint        | ArchLinux                    | Fedora      | Mac OS X | Mandatory? |
|----------+---------+---------------------------+------------------------------+-------------+----------+------------|
| [[http://www.tug.org/texlive/][texlive]]  |         | texlive-full latex-beamer | texlive-most texlive-langcjk | texlive-all |          | Yes        |
| [[http://beyondgrep.com/][ack-grep]] | ack     | ack-grep                  | ack                          | ack         | ack      | No         |

* El-get packages
  :PROPERTIES:
  :CUSTOM_ID: advanced-el-get-packages
  :END:

#+NAME: advanced-el-get-packages
#+CAPTION: El-get packages matrix for ome-advanced module
|                  | Status      | Description                                   |
|------------------+-------------+-----------------------------------------------|
| [[https://github.com/magnars/expand-region.el][expand-region.el]] | Recommended | Expand and select.                            |
| [[https://github.com/jhelwig/ack-and-a-half][ack-and-a-half]]   | Recommended | Yet another emacs front-end to ack.           |
| [[https://github.com/winterTTr/ace-jump-mode][ace-jump-mode]]    | Recommended | A quick cursor location minor mode for emacs. |

* Expand-region
  :PROPERTIES:
  :CUSTOM_ID: expand-region
  :END:

Often we need to select text. We select since we want to limit our operation to
a small region. For a long time, people select text by =C-@= and then manually
moving the point with =C-f=, =M-f= or something similar.

However, most of the time, we want to select text by semantic unit, such as
sentences, paragraphs, s-exps, code blocks, instead of just select character by
character, or word by word. So there comes [[https://github.com/magnars/expand-region.el][expand-region.el]], created by
[[https://github.com/magnars/expand-region.el][magnars]], the author of [[http://emacsrocks.com/][emacsrocks]].

As its name, =expand-region= can expand/contract the selected region by
 semantic units. Just keep pressing the key until it selects what you
want. Here's a live [[http://emacsrocks.com/e09.html][demo]] of expand-region from emacsrocks.

#+NAME: expand-region
#+BEGIN_SRC emacs-lisp
  (defun ome-expand-region-setup ()
    (global-set-key (kbd "C-=") 'er/expand-region))

  (ome-install 'expand-region)
#+END_SRC

* Ace-jump-mode
  :PROPERTIES:
  :CUSTOM_ID: ace-jump-mode
  :END:

[[https://github.com/winterTTr/ace-jump-mode][ace-jump-mode]] is a minor mode for Emacs, enabling fast/direct cursor movement
in current view. "You can move your cursor to ANY position (across window and
frame) in emacs by using only 3 times key press."

To tell the truth, I still don't why it it called "ace-jump". Seems [[https://github.com/johnlindquist/AceJump][AceJump]]
first appears as an [[http://www.jetbrains.com/idea/][Intellij]] [[http://plugins.jetbrains.com/plugin/7086?pr%3DphpStorm][plugin]]. [[http://www.vim.org/scripts/script.php?script_id%3D3526][EasyMotion]] provides a similar feature to
Vim.

#+NAME: ace-jump-mode
#+BEGIN_SRC emacs-lisp
  (defun ome-ace-jump-mode-setup ()
    (autoload
      'ace-jump-mode
      "ace-jump-mode"
      "Emacs quick move minor mode"
      t)
    ;; you can select the key you prefer to
    (define-key global-map (kbd "C-c SPC") 'ace-jump-mode)

    ;;
    ;; enable a more powerful jump back function from ace jump mode
    ;;
    (autoload
      'ace-jump-mode-pop-mark
      "ace-jump-mode"
      "Ace jump back:-)"
      t)
    (eval-after-load "ace-jump-mode"
      '(ace-jump-mode-enable-mark-sync))
    (define-key global-map (kbd "C-x SPC") 'ace-jump-mode-pop-mark)
    )

  (ome-install 'ace-jump-mode)
#+END_SRC

* Ack-and-a-half
  :PROPERTIES:
  :CUSTOM_ID: ack-and-a-ha
  :END:

As we all know, Emacs is a good text editor. However, in some cases, we may
spend most of our time to text reading instead of editing. As an advanced Emacs
user, you may know [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Grep-Searching.html][grep-find]], and you may also know that you can jump to the
next matching item by =M-g n=, oh, that's cool, really. But you still need to
specify what type of file to search. You don't want to touch binary files with
Emacs, ha? And, certainly you do want to ignore some hidden files such as files
and directories used by various version control system. So there comes [[http://beyondgrep.com/][ack]],
which works as expected.

With the help of [[https://github.com/jhelwig/ack-and-a-half][ack-and-a-half]], just go to the right place, then =M-x ack=,
you'll get all you need. Enjoy it.

#+NAME: ack-and-a-half
#+BEGIN_SRC emacs-lisp
  (when (or (executable-find "ack") (executable-find "ack-grep"))
    (ome-install 'ack-and-a-half))
#+END_SRC

* Todo
* Footnotes
[1] See [[http://vimgolf.com/][vimgolf]] for funny things.
