#+TITLE: Oh My Emacs Advanced
#+OPTIONS: toc:2 num:nil ^:nil

This is part of the [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]].

This file contains some advanced features or packages which could make emacs
look unlike emacs. So ensure you have some basic knowledge and experience
before loading this file.

* Prerequisites
  :PROPERTIES:
  :CUSTOM_ID: advanced-prerequisites
  :END:

#+NAME: advanced-prerequisites
#+CAPTION: Prerequisites for ome-advanced module
|          | Windows | Ubuntu/Debian/Mint        | ArchLinux                    | Fedora      | Mac OS X | Mandatory? |
|----------+---------+---------------------------+------------------------------+-------------+----------+------------|
| [[http://www.tug.org/texlive/][texlive]]  |         | texlive-full latex-beamer | texlive-most texlive-langcjk | texlive-all |          | Yes        |
| [[http://beyondgrep.com/][ack-grep]] | ack     | ack-grep                  | ack                          | ack         | ack      | No         |

Notes:
- [[http://www.tug.org/texlive/][texlive]] is required by evil, since evil need =texi2pdf= to =make
  info=. However, I don't think it is a good idea to install the huge texlive
  just to build evil, so I've made a [[http://gitorious.org/evil/evil/merge_requests/50][patch]] for it.

* El-get packages
  :PROPERTIES:
  :CUSTOM_ID: advanced-el-get-packages
  :END:

#+NAME: advanced-el-get-packages
#+CAPTION: El-get packages matrix for ome-advanced module
|                  | Status      | Description                                   |
|------------------+-------------+-----------------------------------------------|
| [[https://github.com/magnars/expand-region.el][expand-region.el]] | Recommended | Expand and select.                            |
| [[https://github.com/jhelwig/ack-and-a-half][ack-and-a-half]]   | Recommended | Yet another emacs front-end to ack.           |
| [[https://github.com/winterTTr/ace-jump-mode][ace-jump-mode]]    | Recommended | A quick cursor location minor mode for emacs. |

* Expand-region
  :PROPERTIES:
  :CUSTOM_ID: expand-region
  :END:

Often we need to select text. We select since we want to limit our operation to
a small region. For a long time, people select text by =C-@= and then manually
moving the point with =C-f=, =M-f= or something similar.

However, most of the time, we want to select text by semantic unit, such as
sentences, paragraphs, s-exps, code blocks, instead of just select character by
character, or word by word. So there comes [[https://github.com/magnars/expand-region.el][expand-region.el]], created by
[[https://github.com/magnars/expand-region.el][magnars]], the author of [[http://emacsrocks.com/][emacsrocks]].

As its name, =expand-region= can expand/contract the selected region by
 semantic units. Just keep pressing the key until it selects what you
want. Here's a live [[http://emacsrocks.com/e09.html][demo]] of expand-region from emacsrocks.

Again, oh-my-emacs defines two extra lazy keys with the help of =evil-leader=,
thus, in normal-state evil, you can trigger =(er/expand-region)= by =<Leader>
xx=, and then expand/contract the region by hitting =x= or =z=.

If you are in =evil-insert-state=, you can trigger =(er/expand-region)= by
=C-==. Ah, in this case, =smartparens= is your good friend. You can select the
region, then QUOTE the region with =smartparens= pairs. Sounds amazing, ha?
Just try it and you will love it.

#+NAME: expand-region
#+BEGIN_SRC emacs-lisp
  (defun ome-expand-region-setup ()
    (global-set-key (kbd "C-=") 'er/expand-region))

  (ome-install 'expand-region)
#+END_SRC

* Ace-jump-mode
  :PROPERTIES:
  :CUSTOM_ID: ace-jump-mode
  :END:

[[https://github.com/winterTTr/ace-jump-mode][ace-jump-mode]] is a minor mode for Emacs, enabling fast/direct cursor movement
in current view. "You can move your cursor to ANY position (across window and
frame) in emacs by using only 3 times key press."

To tell the truth, I still don't why it it called "ace-jump". Seems [[https://github.com/johnlindquist/AceJump][AceJump]]
first appears as an [[http://www.jetbrains.com/idea/][Intellij]] [[http://plugins.jetbrains.com/plugin/7086?pr%3DphpStorm][plugin]]. [[http://www.vim.org/scripts/script.php?script_id%3D3526][EasyMotion]] provides a similar feature to
Vim.

#+NAME: ace-jump-mode
#+BEGIN_SRC emacs-lisp
  (defun ome-ace-jump-mode-setup ()
    ; ...
    )

  (ome-install 'ace-jump-mode)
#+END_SRC

* Ack-and-a-half
  :PROPERTIES:
  :CUSTOM_ID: ack-and-a-ha
  :END:

As we all know, Emacs is a good text editor. However, in some cases, we may
spend most of our time to text reading instead of editing. As an advanced Emacs
user, you may know [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Grep-Searching.html][grep-find]], and you may also know that you can jump to the
next matching item by =M-g n=, oh, that's cool, really. But you still need to
specify what type of file to search. You don't want to touch binary files with
Emacs, ha? And, certainly you do want to ignore some hidden files such as files
and directories used by various version control system. So there comes [[http://beyondgrep.com/][ack]],
which works as expected.

With the help of [[https://github.com/jhelwig/ack-and-a-half][ack-and-a-half]], just go to the right place, then =M-x ack=,
you'll get all you need. Enjoy it.

#+NAME: ack-and-a-half
#+BEGIN_SRC emacs-lisp
  (when (or (executable-find "ack") (executable-find "ack-grep"))
    (ome-install 'ack-and-a-half))
#+END_SRC

* Todo
*** Evil mode
- I only enable =evil-local-mode= for =text-mode= and =prog-mode=, but I don't
  know why =evil-local-mode= is enabled for =magit-log-mode= by default and
  shadowed a lot of =magit= keybindings?
- Evil has some conflicts with smartparens due to cursor position. I should
  temporarily disable =evil-local-mode= when I do operations like
  =sp-up-sexp=. Maybe I can get this by =post-command-hook= or smartparens's
  =post-command-handler=? Or just use =defadvice=?

* Footnotes
[1] See [[http://vimgolf.com/][vimgolf]] for funny things.
