#+TITLE: Oh My Emacs Auto-mode
#+OPTIONS: toc:nil num:nil ^:nil

This is part of the [[https://github.com/xiaohanyu/oh-my-emacs][oh-my-emacs]].

This file contains various settings for minor file types, such as SCons build
file, archlinux's PKGBUILD file, etc.

* SCons
  :PROPERTIES:
  :CUSTOM_ID: scons
  :END:

[[http://www.scons.org/][SCons]] is a next generation build system that is much easier to configure and
use than the traditional make utility. SCons uses the Python general purpose
programming language as a foundation, and all SCons build files are Python
scripts, so we just set SCons build file work with python-mode.

#+NAME: scons
#+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("SConstruct" . python-mode))
#+END_SRC

* YAML
  :PROPERTIES:
  :CUSTOM_ID: yaml
  :END:

[[http://www.yaml.org/][YAML]] is a human friendly data serialization standard for all programming
languages. I really like it for its simplicity and readability. However, Emacs
didn't have a builtin mode for editing YAML files, so you know how easy to
solve this by adopting =el-get=. Thanks =el-get= again!

#+NAME: yaml
#+BEGIN_SRC emacs-lisp
  (defun ome-yaml-mode-setup ()
    (add-hook 'yaml-mode-hook
              (lambda ()
                (linum-mode 1))))

  (ome-install 'yaml-mode)
#+END_SRC
